
# Google Sheets Configuration
[google_sheets]
sheet_url = "https://docs.google.com/spreadsheets/d/1u18KjdajMQeWn4AWL_2a-OiF4AeN8RC5DkAKnmQcfsw/edit?gid=0#gid=0"

[google_sheets_service_account]
type = "service_account"
project_id = "silken-bastion-466005-k8"
private_key_id = "857a58dd3c93f01f21efe4a33bc8704eb7abcb6d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCkHCagoTIJ8ZGg
JzRiKyulG9/wmP6U341wKfsjSYQ2OHXnolUfwvcO9qLJbDVPecOAdmKbaz8JIaKz
U0+0CySk1kpMoCh9oAt9Z4QW+BD6BSWWKMhA3wJ0doD3dU5/RIfOirAX/YUk5A0E
hYCXAbsIDTqk2mYsor7kDSSZAX3prr0UVt+MgPFxIfrIwPe7SCypcGuF70ceBY/1
QUJohJRLKWm4XHxyYGtHaIqdXbqkcUknHmM0tM6DPakCNjPJzazS2+XmdqzBL98D
hG1NdfdqVDqyygnvLV6eWHUdcG/ZZeJyYFrrr86LiOJ7Zv9K3EMutA0hzJiMNo1+
7vIjuKR5AgMBAAECggEAEriqE22wMVWJ4QpNPdxiPeirKF2xFTdXgZyDFih0g7b3
Lws5c3EgvBKYyX+lqUELyM44kOBa2uYnvcCwTqrCwxHgfKinVdrPKhQytmgVj7V3
RI+3IJIQS/bviXYBaXVeRMqqLLfIMPLZz/08M9MyYfMYZea1pzvoU53IN12QiVAu
BX/NG+YHIzcCBVeFJuBnc5DN+DTa7gcQLavjETMb424tu2blZP2HJ1IGniimfdQ0
/eoY7zESMIwR0LvImAQdRxLULLg4KfrBC8weICQvlJp6oMElJp8WeW8nw0o0NNTe
pLX1KiI0ss++RPek54KLtPp5tGFoWgQQOI0SvslvjQKBgQDVpXnbWjq++VSP8Fc5
VmbiVWJSaq5lX3Q0OUtHXr2V8iTDFFGKJIc9Ta63XBEEpUcbiZ5DDXFAg+hH91ND
hq7ZGBgyS96EeO7Gq58TJBIHI1vqMzKOzs4lCVgoiIEMF9tHE1ZJ6dPW6XxVxMA2
LDyPcFjCNelWhLGTBJZfbrx5JwKBgQDEpLVSOzq2sEAD5HKPpBfqvST/pz/oL5CK
eKyfJ3hQs96jL3PBQ03+rpJBddnavoEoTbzi631aPMyhIFXXZfz2tNZJQRLqrNjL
gna4jmolUwhGQJKQmpJAsqH1F1mrWoGqQf5TbrMuHzKT4T1E/P6rO9hUiWrFjCUb
Ga8UWYI5XwKBgEJdotrWzoTgYrpLyGyRQGhyaZZ8eSwYWLqYSaAj9/SKQY0v1Jx6
+F+8r9dZjBfLV6lgOH9Pv6xwzUj9tSm2vr3FVE7bboXsIxAn48RIYilBfJ3lxYDD
ERpEKtR8gsnE52LOyPEw55NM+EiUU7kASNet6IR7xr4PfjHTLPr8JSPlAoGAC3iM
NzrLRwLrCQ8Xe7eXyZK1CNDJ0pKLvPgjIbmctCB5+Uz4VKrHbvbiAz2Lss3wHNjE
DvyruErZqQCI4WLKqd2MroNERjpE/0IiCMwN9xVr4yU7J4JMy8df2Ts+eNdzvunQ
my9W9nbNbYDzIQYdGQIJsYy+lL2DIJyT8PzzssMCgYAkY5nYxm+Etwm7lt9fnrB7
UzTZTL5DftBj9BQPVjvIm2A0NiCatElVrNAjBfrr7Y6IXw8zASb+suqMer1LSguw
64pEm1OStvGPzp+lsZae+9EExIJTNx+c7hIfnSsdlW7LtTvnXUxOHIh0bfi4N14e
bM+Tmx7tVfyh+rn+TembCA==
-----END PRIVATE KEY-----"""
client_email = "alumnidashboard@silken-bastion-466005-k8.iam.gserviceaccount.com"
client_id = "108020304865727966460"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/alumnidashboard%40silken-bastion-466005-k8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
